### ISSUE TITLE
Center text in buttons

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/elena_task#1]
![image](https://user-images.githubusercontent.com/8848858/46920121-19ff5800-cff2-11e8-8373-7c1a5c888237.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/46920774-ce51ac00-cffb-11e8-9272-0ddd0d98bcc6.png)

**Comment by anastasiia-emets** [comment]
так нормально чи ні? я не можу зрозуміти в чому проблема.

**Comment by rudnitskih** [comment]
понял, у меня на MacOS для кнопок снизу и сверху дополнительный padding есть

![image](https://user-images.githubusercontent.com/8848858/47023567-961bac00-d168-11e8-8a78-43c30ec34ed5.png)

**Comment by rudnitskih** [comment]
Это скриншот блочной модели button, тебе нужно `padding: 0` для всех кнопок поставить
