### ISSUE TITLE
Blocks are not centered

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/elena_task#2]
![image](https://user-images.githubusercontent.com/8848858/46920133-65196b00-cff2-11e8-90ae-78fa5158120f.png)

**Comment by anastasiia-emets** [comment]
а відносно чого їх центрувати? відносно один одного?

**Comment by rudnitskih** [comment]
Відносно центру єкрану:
<img width="1440" alt="screen shot 2018-10-14 at 23 13 58" src="https://user-images.githubusercontent.com/8848858/46921673-ff83a980-d006-11e8-8e8b-179ab7120adf.png">

<img width="1440" alt="screen shot 2018-10-14 at 23 15 14" src="https://user-images.githubusercontent.com/8848858/46921676-07dbe480-d007-11e8-9563-637c37a93ce6.png">

**Comment by rudnitskih** [comment]
Средний елемент (иконка сердечко) должна быть ровно по середине.

**Comment by rudnitskih** [comment]
так элементы центрировать нельзя, на слудеющем уроке разберись как это нужно сделать правильно будет.

![image](https://user-images.githubusercontent.com/8848858/47023252-f100d380-d167-11e8-9e0a-8beedfce1011.png)
